name: changelog

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]

jobs:
  enforce-label:
    runs-on: ubuntu-latest
    steps:
      - uses: yogevbd/enforce-label-action@2.1.0
        with:
          REQUIRED_LABELS_ANY: "include-changelog,exclude-changelog"
          REQUIRED_LABELS_ANY_DESCRIPTION: "Enforcing that a PR must have one of these labels to be merged"
